a=int(input("enter the number:"))
b=int(input("enter the number:"))
print("the entered numbers are",a,"and",b)
print("the sum of the numbers is:",a+b)
print("the difference of the numbers is:",a-b)
print("the product of the numbers is:",a*b)
print("the integer quotient of the numbers is:",a//b)
print("the remainder of the two numbers is:",a%b)